version: '3.8'

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: images
      POSTGRES_USER: Arseniy
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
      - rabbitmq
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./dockerstatic:/fastapi/app/static

  image_processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    depends_on:
      - rabbitmq
      - fastapi_app
    volumes:
      - ./dockerstatic:/app/static

volumes:
  pg_data:
